[package]
name = "Fourth_Laboratory_Computer_Graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.19.0"
minifb = "0.27.0"
tobj = "4.0.2"
fastnoise-lite = "1.1.1"
rand = "0.8.5"